server:
  port: 8084

spring:
  application:
    name: trip-service
  datasource:
    url:
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host:
      port:

  kafka:
    bootstrap-servers: 192.168.1.100:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        linger.ms: 50
        batch.size: 131072
        request.timeout.ms: 30000
    consumer:
      group-id: trip-service-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: true
        spring.json.trusted.packages: "*"
        max.poll.records: 500
        spring.json.type.mapping: >
          com.example.matching_service.dto.kafka.TripMatchedEvent:com.example.trip_service.kafka.dto.TripMatchedEvent,
          com.example.payment_service.kafka.dto.PaymentCompletedEvent:com.example.trip_service.kafka.dto.PaymentCompletedEvent,
          com.example.payment_service.kafka.dto.PaymentFailedEvent:com.example.trip_service.kafka.dto.PaymentFailedEvent,
          com.example.geospatial_service.kafka.dto.DriverLocationUpdatedEvent:com.example.trip_service.kafka.dto.DriverLocationUpdatedEvent
    listener:
      ack-mode: RECORD

resilience4j:
  circuitbreaker:
    instances:
      driver-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 20
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 5
      user-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 20
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 5
      naver-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: count-based
        sliding-window-size: 20
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
  timelimiter:
    instances:
      driver-service:
        timeout-duration: 3s
        cancel-running-future: true
      user-service:
        timeout-duration: 3s
        cancel-running-future: true
      naver-service:
        timeout-duration: 5s
        cancel-running-future: true

naver:
  api:
    client-id:
    client-secret:

services:
  user-service:
    url: http://user-service
  driver-service:
    url: http://driver-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka